---
title: "libcbm_exn"
author: "Scott Morken and Alex Chubaty"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{libcbm_exn}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r setup}
library(reticulate)
library(libcbmr)
```

# Usage examples

## Example 0

Adapted from: <https://github.com/cat-cfs/libcbm_py/blob/cbm_exn/examples/model_definition.rmd>.

```{r usage-example0, eval = FALSE}
model_definition <- import("libcbm.model.model_definition")

pool_def <- dict(
  Input = 0,
  WoodyBiomass = 1,
  Foliage = 2,
  SlowDOM = 3,
  MediumDOM = 4,
  FastDOM = 5,
  CO2 = 6,
  Products = 7
)

processes <- dict(
  GrowthAndMortality = 0,
  Decay = 1,
  Disturbance = 2
)

flux_indicators <- c(
  dict(
    name = "NPP",
    process_id = processes["GrowthAndMortality"],
    source_pools = list(
      pool_def["Input"],
      pool_def["Foliage"]
    ),
    sink_pools = list(
      pool_def["WoodyBiomass"],
      pool_def["Foliage"],
      pool_def["FastDOM"]
    )
  ),
  dict(
    name = "DecayEmissions",
    process_id = processes["Decay"],
    source_pools = list(
      pool_def["SlowDOM"],
      pool_def["MediumDOM"],
      pool_def["FastDOM"]
    ),
    sink_pools = c(
      pool_def["CO2"]
    )
  ),
  dict(
    name = "DisturbanceEmissions",
    process_id = processes["Disturbance"],
    source_pools = list(
      pool_def["WoodyBiomass"],
      pool_def["Foliage"],
      pool_def["SlowDOM"],
      pool_def["MediumDOM"],
      pool_def["FastDOM"]
    ),
    sink_pools = c(
      pool_def["CO2"]
    )
  ),
  dict(
    name = "HarvestProduction",
    process_id = processes["Disturbance"],
    source_pools = list(
      pool_def["WoodyBiomass"],
      pool_def["Foliage"],
      pool_def["MediumDOM"]
    ),
    sink_pools = list(
      pool_def["Products"]
    )
  )
)

weibull_cumulative <- function(x, k = 2.3, y = 1) {
  c <- (x / y)^k
  return(1 - exp(-c))
}

get_npp_matrix <- function(model, age) {
  # creates NPP flows based on an age passed to the cumulative weibull distribution
  n_stands <- length(age)
  npp <- matrix(weibull_cumulative((age + 1) / 100.0) - weibull_cumulative(age / 100.0))
  op <- model$create_operation(
    matrices = list(
      list("Input", "WoodyBiomass", npp),
      list("Input", "Foliage", npp / 10.0)
    ),
    fmt = "repeating_coordinates"
  )
  op$set_matrix_index(matrix(seq(0, n_stands - 1)))
  return(op)
}

get_mortality_matrix <- function(model, n_stands) {
  op <- model$create_operation(
    matrices = list(
      list("WoodyBiomass", "WoodyBiomass", 1.0),
      list("WoodyBiomass", "MediumDOM", 0.01),
      list("Foliage", "Foliage", 1.0),
      list("Foliage", "FastDOM", 0.95)
    ),
    fmt = "repeating_coordinates"
  )
  # set every stand to point at the 0th matrix:
  # they all share the same simple mortality matrix
  op$set_matrix_index(matrix(rep(0, n_stands)))
  return(op)
}

get_decay_matrix <- function(model, n_stands) {
  op <- model$create_operation(
    matrices = list(
      list("SlowDOM", "SlowDOM", 0.97),
      list("SlowDOM", "CO2", 0.03),
      list("MediumDOM", "MediumDOM", 0.85),
      list("MediumDOM", "SlowDOM", 0.10),
      list("MediumDOM", "CO2", 0.05),
      list("FastDOM", "FastDOM", 0.65),
      list("FastDOM", "MediumDOM", 0.25),
      list("FastDOM", "CO2", 0.10)
    ),
    fmt = "repeating_coordinates"
  )
  op$set_matrix_index(matrix(rep(0, n_stands)))
  return(op)
}

disturbance_type_ids <- c(
  none = 0,
  fire = 1,
  harvest = 2
)

get_disturbance_matrix <- function(model, disturbance_types) {
  no_disturbance <- list()
  fire_matrix <- list(
    list("WoodyBiomass", "WoodyBiomass", 0.0),
    list("WoodyBiomass", "CO2", 0.85),
    list("WoodyBiomass", "MediumDOM", 0.15),
    list("Foliage", "Foliage", 0.0),
    list("Foliage", "CO2", 0.95),
    list("Foliage", "FastDOM", 0.05)
  )
  harvest_matrix <- list(
    list("WoodyBiomass", "WoodyBiomass", 0.0),
    list("WoodyBiomass", "Products", 0.85),
    list("WoodyBiomass", "MediumDOM", 0.15),
    list("Foliage", "Foliage", 0.0),
    list("Foliage", "FastDOM", 1.0)
  )
  op <- model$create_operation(
    matrices = list(
      no_disturbance, fire_matrix, harvest_matrix
    ),
    fmt = "matrix_list"
  )
  op$set_matrix_index(matrix(disturbance_types))
  return(op)
}

with(model_definition$create_model(pool_def, flux_indicators) %as% model, {
  output_processor <- model$create_output_processor()
  n_stands <- 20000
  vars <- model$allocate_model_vars(n_stands)
  vars$pools["Input"]$assign(1.0)
  stand_age <- rep(0, n_stands)
  timesteps <- 0:100
  for (t in timesteps) {
    print(t)
    # add some simplistic disturbance scheduling
    disturbance_types <- sample(c(0, 1, 2), n_stands, replace = TRUE, prob = c(0.995, 0.003, 0.002))

    # reset flux at start of every time step
    vars$flux$zero()

    # prepare the matrix operations
    operations <- list(
      get_disturbance_matrix(model, disturbance_types),
      get_npp_matrix(model, stand_age),
      get_mortality_matrix(model, n_stands),
      get_decay_matrix(model, n_stands)
    )

    # associate each above operation with a flux indicator category
    op_processes <- list(
      processes["Disturbance"],
      processes["GrowthAndMortality"],
      processes["GrowthAndMortality"],
      processes["Decay"]
    )

    # enabled array can be used to disable(0)/enable(1)
    # dynamics per index
    vars$enabled$assign(rep(1, n_stands))

    model$compute(vars, operations, op_processes)
    for (op in operations) {
      op$dispose()
    }
    output_processor$append_results(t, vars)
    stand_age[disturbance_types != 0] <- 0
    stand_age <- stand_age + 1
  }
})
```

## Example 1

```{r usage-example1, eval = FALSE}
cbm_exn_model <- import_from_path("libcbm.model.cbm_exn.cbm_exn_model",
                                  path = system.file("python", package = "libcbmr"),
                                  delay_load = TRUE)

dict(a = 1)
print(py_get_item(dict(a = 1), "a"))

spinup_increments <- data.frame(
  # `row_idx` is the sequential index of the rows in
  # spinup_parameters, and the number of stands the the
  # number of unique values in this column
  row_idx = c(1, 1, 1, 2, 2, 2), # 1 based indexing in R right?
  age = c(0, 1, 2, 0, 1, 2),
  merch_c_inc = c(0, 1, 2, 0, 1, 2),
  foliage_c_inc = c(0, 1, 2, 0, 1, 2),
  other_c_inc = c(0, 1, 2, 0, 1, 2)
)

spinup_parameters <- data.frame(
  age = c(0, 50), # age at end of spinup
  area = c(NA, NA), # area is not internally required by CBM, but needed for results processing
  delay = c(0, 0), # delay cbm spinup parameter
  species = c(1, 2), # has effect on disturbances
  min_rotations = c(10, 10),
  max_rotations = c(30, 30),
  return_interval = c(150, 150),
  historical_disturbance_type = c(1, 1),
  last_pass_disturbance_type = c(1, 1),
  mean_annual_temperature = c(-4.0, 2.5),
  enabled = c(TRUE, TRUE)
)

# config_dir is a directory containing parameters in json format to run cbm_exn_model
# - these parameters consist of all CBM3 like parameters
# - derived from a cbm_defaults database, pool, and flux indicator configuration

config_dir <- "inst/config" ## TODO: resume here; need json params

with(cbm_exn_model$initialize(config_dir) %as% cbm, {
  # the spinup function creates the t=0 cbm_vars
  # but you can save and or load cbm_vars for each
  # timestep at the end of spinup point
  cbm_vars <- cbm$spinup(
    dict(
      spinup_increments = spinup_increments,
      spinup_parameters = spinup_parameters
    )
  )
})

## ---------------------------------------------------------------------------------------------- ##
## the remainder of this script would be more or less repeated for each simulation timestep

# the following are reqular R dataframes pulled out of the cbm_vars object
pools_df <- py_get_item(cbm_vars, "pools")
flux_df <- py_get_item(cbm_vars, "flux")
state_df <- py_get_item(cbm_vars, "state")
params_df <- py_get_item(cbm_vars, "parameters")

# update cbm_vars as needed, however note all of the member dataframes
# must have the same number of rows at all times as they are row-aligned

# set the disturbance types array
params_df$disturbance_type <- c(0, 1)

# set the C increments for this timestep
params_df$merch_c_inc <- c(0, 1.5)
params_df$merch_c_inc <- c(0, 0.5)
params_df$foliage_c_inc <- c(0, 0.1)

params_df$mean_annual_temperature <- c(-1.1, -3.0)

with(cbm_exn_model$initialize(config_dir) %as% cbm, {
  # internally the pools, flux, and state dataframes will be updated by this
  # function call
  cbm_vars <- cbm$step(
    dict(
      "pools" = pools_df,
      "flux" = flux_df,
      "state" = state_df,
      "parameters" = params_df
    )
  )
})

# the end of each CBM timestep, pass cbm_vars to results processing as needed
```
